"""
Plan Refiner for RDD Planner

This module refines RDD-generated plans by:
- Removing redundant subtasks
- Simplifying the structure
- Ensuring logical ordering
- Eliminating duplicates and circular dependencies
"""

from typing import Any, Optional
from dataclasses import dataclass
from pathlib import Path


@dataclass
class RefinerConfig:
    """Configuration for plan refinement"""
    prompt_dir: Any = None  # Will use same prompt_dir as RDDConfig
    max_iterations: int = 3  # Maximum refinement iterations
    

class PlanRefiner:
    """
    Refines hierarchical plans generated by RDD planner.
    
    Uses LLM to simplify and improve plan quality by removing redundancy,
    improving clarity, and ensuring logical task ordering.
    """
    
    def __init__(self, llm: Any, config: Optional[RefinerConfig] = None):
        """
        Initialize the plan refiner.
        
        Args:
            llm: Language model for refinement (same as used by RDD planner)
            config: Optional configuration for refinement
        """
        self.llm = llm
        self.config = config or RefinerConfig()
        
        # Set default prompt directory if not specified
        if self.config.prompt_dir is None:
            self.config.prompt_dir = Path(__file__).parent / "prompts"
        
        # Load refine prompt template
        self.refine_prompt_template = self._load_prompt("refine_prompt.txt")
    
    def _load_prompt(self, filename: str) -> str:
        """Load a prompt template from file"""
        path = Path(self.config.prompt_dir) / filename
        with open(path, 'r') as f:
            return f.read()
    
    def _get_refinement_prompt(self, plan: str, task: str) -> str:
        """
        Generate prompt for plan refinement.
        
        Args:
            plan: The current plan text
            task: Original task description
        
        Returns:
            Formatted prompt for the LLM
        """
        return self.refine_prompt_template.format(task=task, plan=plan)
    
    def refine(self, plan: str, task: str, max_iterations: Optional[int] = None) -> dict:
        """
        Refine the given plan to improve quality and remove redundancy.
        
        Args:
            plan: The hierarchical plan text to refine
            task: Original task description
            max_iterations: Maximum number of refinement iterations (default from config)
        
        Returns:
            Dictionary with:
                - refined_plan: The improved plan text
                - iterations: Number of iterations performed
                - improvement_notes: List of improvements made
        """
        max_iter = max_iterations or self.config.max_iterations
        current_plan = plan
        improvement_notes = []
        
        print(f"\n🔧 Refining plan with LLM (max {max_iter} iterations)...")
        
        for iteration in range(1, max_iter + 1):
            print(f"\n  Iteration {iteration}/{max_iter}")
            
            # Generate refinement prompt (LLM will identify issues itself)
            prompt = self._get_refinement_prompt(current_plan, task)
            
            # Get refined plan from LLM
            messages = [{"role": "user", "content": prompt}]
            response_obj = self.llm(messages)
            refined_plan = response_obj["content"].strip()
            
            # Remove "CURRENT PLAN:" prefix if LLM included it
            if refined_plan.startswith("CURRENT PLAN:"):
                refined_plan = refined_plan.replace("CURRENT PLAN:", "", 1).strip()
            
            # Check if refinement made meaningful changes
            if refined_plan.lower() == current_plan.lower():
                print("  ⚠ No changes made - plan is already optimal")
                break
            
            # Track improvements
            old_lines = len(current_plan.split('\n'))
            new_lines = len(refined_plan.split('\n'))
            
            if new_lines < old_lines:
                improvement = f"Reduced from {old_lines} to {new_lines} lines"
                improvement_notes.append(improvement)
                print(f"  ✓ {improvement}")
            else:
                print(f"  ✓ Improved structure")
            
            current_plan = refined_plan
        
        print(f"\n✅ Refinement complete\n")
        
        return {
            "refined_plan": current_plan,
            "original_plan": plan,
            "iterations": iteration,
            "improvement_notes": improvement_notes,
        }
